# Python Training

Welcome to Python training at 84.51$^\circ$! The tutorial is in 6 parts: <br>
   >  Python Basics<br>
    > Numpy<br>
    > Matplotlib<br>
   > Pandas<br>
   > 84.51$^\circ$ Specific<br>
   > Small case study<br>

By the end, you'll hopefully have a good enough understanding of Python to get working on your own projects

# Numpy Exercise Solutions

### 1. Create a 3x3 array of random values and a 3x1 array of random values. Multiply them and print the result.

In [2]:
import numpy as np
a = np.random.random((3,3))
b = np.random.random((3,1))
# Multiply them using the np.dot function
# (regular multiply would multiply element-by-element)
ab = np.dot(a, b)
print(ab)

[[ 0.72918051]
 [ 0.94701895]
 [ 0.23013407]]


### 2. Create a 5x5 random matrix, reshape it to 25x1, and normalize it. Print the new mean and standard deviation.

In [3]:
a = np.random.random((5,5))
a = a.reshape((25,1))
amax = a.max()
amin = a.min()
a = (a - amin) / (amax - amin)
print(a)
print("Standard Deviation: " + str(a.std()))
print("mean: " + str(a.mean()))

[[ 0.5658785 ]
 [ 0.78265768]
 [ 0.        ]
 [ 0.87660273]
 [ 0.23334801]
 [ 0.867682  ]
 [ 0.73286547]
 [ 0.79945365]
 [ 0.01581276]
 [ 0.61898493]
 [ 0.2003406 ]
 [ 0.07916423]
 [ 0.00754676]
 [ 1.        ]
 [ 0.48635532]
 [ 0.46832229]
 [ 0.55466679]
 [ 0.86155716]
 [ 0.8596511 ]
 [ 0.99414352]
 [ 0.60571099]
 [ 0.73127014]
 [ 0.24194352]
 [ 0.35559024]
 [ 0.85338417]]
Standard Deviation: 0.319550329559
mean: 0.551717301369


### 3. Create a 1000x1 random matrix. Remove values above the 99th percentile.

In [3]:
a = np.random.random(size=1000)
a_sorted = np.sort(a)
# The 99th percentile will be the value at 99/100 * N
cutoff_index = .99 * a_sorted.shape[0]
# Force the cutoff_index to be an integer
cutoff_index = int(cutoff_index)
# The value at this position is the 99th percentile
cutoff_value = a_sorted[cutoff_index]

# Keep only the values below this threshold
print("99th percentile: %f" % cutoff_value)
new_a = a[a <= cutoff_value]
print(new_a)

99th percentile: 0.992007
[  1.41269524e-01   3.96703066e-01   2.67399085e-01   3.58078672e-01
   6.33588191e-01   6.65541889e-01   3.71181868e-01   9.52592529e-01
   9.59191924e-01   1.96297568e-01   6.64070534e-01   8.59561924e-01
   4.06017546e-02   5.54808541e-01   6.85501073e-01   8.35745972e-01
   7.92957724e-01   2.94762253e-01   6.83981037e-02   2.45958956e-01
   4.76219507e-01   4.31114427e-01   1.03642381e-01   4.11595062e-01
   6.70781040e-01   9.47825480e-01   2.44626479e-01   8.37865348e-01
   6.41710157e-01   5.32991275e-01   4.16355676e-01   6.65989921e-02
   1.79429390e-02   3.96458632e-01   4.67028671e-01   1.00847198e-01
   6.13938752e-01   6.29282329e-01   7.13903830e-01   9.87922925e-01
   4.98848132e-01   3.88903286e-01   7.49413177e-01   5.01309514e-01
   3.45155380e-01   7.19908082e-01   5.88806366e-01   4.20544342e-01
   2.53849661e-01   9.85335654e-01   3.75381927e-01   3.15568739e-01
   3.55544243e-01   4.84640017e-01   3.17712545e-01   9.03794301e-01
   9.341

### 4. Create a 5x5 matrix with row values ranging from 0 to 4.

In [4]:
# start by building out a 5 x 5 matrix of zeroes
Z = np.zeros((5,5))
print(Z)

print("")
print("----ANSWER BELOW----")
print("")
# use np.arange to add ('+=') values from 0-4 across each row of Z
Z += np.arange(5)
print(Z)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

----ANSWER BELOW----

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


### 5. Create a 2-dimensional NumPy array of random intengers that has a shape of 3 rows and 4 columns. Force the array to have a low value of 500, and a high value of 5000 (consider researching 'np.random.randint' function for support). Print the mean & median of each column. Then do the same for each row. 

In [5]:
# start by building out the 3 x 4 array 
# we can use the 'low' and 'high' arguments 
# 'size' argument allows us to specify shape 
q_5 = np.random.randint(low = 500, high = 5000, size = (3,4))
print(q_5)
print(q_5.shape)

[[2850 3899 1698 2761]
 [3220 4938 2976 4517]
 [3511  797 4607 1968]]
(3, 4)


In [6]:
# we can use 'axis' to specify column or row 
# axis = 0 represents column
# axis = 1 represents row 

# find the mean & median: columns 
print(np.mean(q_5, axis = 0))
print(np.median(q_5, axis = 0))

[ 3193.66666667  3211.33333333  3093.66666667  3082.        ]
[ 3220.  3899.  2976.  2761.]


In [7]:
# find the mean & median: rows 
print(np.mean(q_5, axis = 1))
print(np.median(q_5, axis = 1))

[ 2802.    3912.75  2720.75]
[ 2805.5  3868.5  2739.5]
